name: Nightly

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
    # Signing INFO
    NIGHTLY_STORE_FILE: ../debug.keystore
    NIGHTLY_PASSWORD: android
    NIGHTLY_KEY_ALIAS: androiddebugkey

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate changelog
        run: |
          echo "## Changelog" >> $GITHUB_STEP_SUMMARY
          sh ./scripts/list-nightly-commits.sh >> $GITHUB_STEP_SUMMARY

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: |
          echo ${NIGHTLY_STORE_FILE} | base64 -d > debug.keystore
          NIGHTLY_KEY_ALIAS=$(echo -n $NIGHTLY_KEY_ALIAS | base64 -d)
          ./gradlew assembleNightly -Dnightly_store_file=${NIGHTLY_STORE_FILE} -DNIGHTLY_PASSWORD="${NIGHTLY_PASSWORD}" -Dnightly_key_alias="${NIGHTLY_KEY_ALIAS}" -Dnightly_key_password="${NIGHTLY_PASSWORD}"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Trail-Sense-Nightly.apk
          path: ./app/build/outputs/apk/nightly/*.apk
          retention-days: 7
